[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "elkopy"
version = "0.1.0"
description = "A Python package for Electronic Coupling calculations in EET processes."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "pyscf",
    "psutil"
]

[project.scripts]
elkopy = "scripts.run_elkopy:main"
elkoplot = "scripts.run_plot:main"

[tool.setuptools]
packages = ["elkopy", "scripts"]